app/blueprints/post_blueprint/views.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, flash

from flask_paginate import Pagination

from app.blueprints.auth import UserDetect
from app.blueprints.post_blueprint.dao.post_dao import Post
from app.exceptions import BaseAppException
from app.paths import DATA_JSON_PATH, COMMENTS_JSON_PATH, USERS_JSON_PATH
from app.logger import logger

post_blueprint = Blueprint('post_blueprint', __name__, template_folder='templates')


@post_blueprint.route('/', methods=['GET'])
def page_index():
    user = UserDetect(request.headers, request.remote_addr, USERS_JSON_PATH)
    user.add_new_user()

    posts = Post(DATA_JSON_PATH, COMMENTS_JSON_PATH)
    all_posts: list[dict] = posts.get_all_posts()

    comments: dict = posts.get_number_comments_with_post_id()

    likes_list = user.get_likes_list()
    bookmarks_list = user.get_bookmarks_list()
    return render_template('index.html', posts=all_posts, comments=comments,
                           likes_list=likes_list, bookmarks_list=bookmarks_list)


@post_blueprint.route('/posts/<int:post_id>/', methods=['GET', 'POST'])
def post_page(post_id: int):
    if request.method == 'POST':
        name: str = request.form.get('name')
        comment: str = request.form.get('comment')
        if name and comment:
            Post(DATA_JSON_PATH, COMMENTS_JSON_PATH).add_new_comment(name, comment, post_id)
            return redirect(url_for('post_blueprint.post_page', post_id=post_id))
        else:
            flash('Заполните все поля для добавления комментария', 'warning')
            return redirect(url_for('post_blueprint.post_page', post_id=post_id), code=302)
    else:
        user = UserDetect(request.headers, request.remote_addr, USERS_JSON_PATH)
        user.add_new_user()

        likes_list = user.get_likes_list()
        bookmarks_list = user.get_bookmarks_list()

        posts = Post(DATA_JSON_PATH, COMMENTS_JSON_PATH)
        post_list: list[dict] = posts.get_post_for_pk(post_id)
        posts.update_views_post(post_id)

        comments_text: list[dict] = posts.get_comments_for_post_by_pk(post_id)
        comments: dict = {
            post_id: len(comments_text)
        }
        return render_template('post.html', posts=post_list, comments_text=comments_text, comments=comments,
                               likes_list=likes_list, bookmarks_list=bookmarks_list)


@post_blueprint.route('/posts/bookmarks/', methods=['GET', 'POST'])
def bookmark_page():
    user = UserDetect(request.headers, request.remote_addr, USERS_JSON_PATH)
    user.add_new_user()

    posts = Post(DATA_JSON_PATH, COMMENTS_JSON_PATH)
    bookmarks_list = user.get_bookmarks_list()
    bookmark_posts: list[dict] = posts.get_bookmark_posts(bookmarks_list)

    comments: dict = posts.get_number_comments_with_post_id()

    likes_list = user.get_likes_list()
    return render_template('bookmarks.html', posts=bookmark_posts, comments=comments,
                           likes_list=likes_list, bookmarks_list=bookmarks_list)


@post_blueprint.route('/posts/bookmark/<int:post_id>/', methods=['POST'])
def get_bookmark(post_id: int):
    user = UserDetect(request.headers, request.remote_addr, USERS_JSON_PATH)
    user.add_new_user()
    user.get_bookmark(post_id)
    return redirect(url_for('post_blueprint.bookmark_page'), code=302)


@post_blueprint.route('/search/', methods=['GET'])
def search_content_page():
    user = UserDetect(request.headers, request.remote_addr, USERS_JSON_PATH)
    user.add_new_user()

    likes_list = user.get_likes_list()
    bookmarks_list = user.get_bookmarks_list()

    per_page = 3
    search_content: str = request.args.get('value', '')
    page = int(request.args.get('page', 1))

    posts = Post(DATA_JSON_PATH, COMMENTS_JSON_PATH)
    list_with_search_posts: list[dict] = posts.search_posts(search_content)
    posts_slice = list_with_search_posts[(page - 1) * per_page:page * per_page]

    comments: dict = posts.get_number_comments_with_post_id()

    pagination = Pagination(page=page, total=len(list_with_search_posts),
                            per_page=per_page, search=False, css_framework='bootstrap4'
                            )
    return render_template('search.html', posts=posts_slice, comments=comments,
                           pagination=pagination, likes_list=likes_list, bookmarks_list=bookmarks_list)


@post_blueprint.route('/users/<string:username>/', methods=['GET'])
def user_posts_page(username: str):
    user = UserDetect(request.headers, request.remote_addr, USERS_JSON_PATH)
    user.add_new_user()

    likes_list = user.get_likes_list()
    bookmarks_list = user.get_bookmarks_list()

    posts = Post(DATA_JSON_PATH, COMMENTS_JSON_PATH)
    user_posts: list[dict] = posts.get_all_post_by_user_name(username)

    comments: dict = posts.get_number_comments_with_post_id()
    return render_template('user-feed.html', posts=user_posts, comments=comments,
                           likes_list=likes_list, bookmarks_list=bookmarks_list)


@post_blueprint.route('/api/posts', methods=['GET'])
def api_get_all_posts_page():
    logger.info('Запрос /api/posts/')
    posts = Post(DATA_JSON_PATH, COMMENTS_JSON_PATH)
    all_posts: list[dict] = posts.get_all_posts()
    return jsonify(all_posts)


@post_blueprint.route('/api/posts/<int:post_id>/', methods=['GET'])
def api_get_post_page(post_id: int):
    logger.info(f'Запрос /api/posts/{post_id}')
    posts = Post(DATA_JSON_PATH, COMMENTS_JSON_PATH)
    return jsonify(posts.get_post_for_pk(post_id))


@post_blueprint.route('/tag/<string:tag_name>/', methods=['GET'])
def search_hashtag(tag_name: str):
    user = UserDetect(request.headers, request.remote_addr, USERS_JSON_PATH)
    user.add_new_user()
    likes_list = user.get_likes_list()
    bookmarks_list = user.get_bookmarks_list()

    per_page = 3
    page = int(request.args.get('page', 1))

    posts = Post(DATA_JSON_PATH, COMMENTS_JSON_PATH)
    list_with_search_posts: list[dict] = posts.search_posts(f'#{tag_name}')
    posts_slice = list_with_search_posts[(page - 1) * per_page:page * per_page]

    comments: dict = posts.get_number_comments_with_post_id()

    pagination = Pagination(page=page, total=len(list_with_search_posts),
                            per_page=per_page, search=False, css_framework='bootstrap4'
                            )
    return render_template('tag.html', posts=posts_slice, comments=comments, pagination=pagination,
                           likes_list=likes_list, tag_name=tag_name, bookmarks_list=bookmarks_list)


@post_blueprint.app_errorhandler(BaseAppException)
def base_error_handler(e: BaseAppException):
    return jsonify({'error': e.message}), e.code


@post_blueprint.route('/posts/like_bookmark/', methods=['POST'])
def get_like_and_bookmark():
    data = request.get_data().decode('utf-8').split('&')
    post_id = int(data[0].replace('post_id=', ''))
    method = ['like' if 'like' in data[1] else 'bookmark' if 'bookmark' in data[1] else ''][0]
    user = UserDetect(request.headers, request.remote_addr, USERS_JSON_PATH)
    user.add_new_user()
    posts = Post(DATA_JSON_PATH, COMMENTS_JSON_PATH)
    status = ''
    likes_count = posts.update_likes_post(post_id)
    bookmarks_list = user.get_bookmarks_list()
    if method == 'bookmark':
        status = user.get_bookmark(post_id)
        bookmarks_list = user.get_bookmarks_list()
    elif method == 'like':
        status = user.get_like(post_id)
        if status:
            likes_count = posts.update_likes_post(post_id, 'like')
        else:
            likes_count = posts.update_likes_post(post_id, 'dislike')
    return jsonify({'status': status,
                    'bookmark_list': len(bookmarks_list),
                    'likes_count': likes_count,
                    })

app/blueprints/post_blueprint/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  {% block user_style %}{% endblock %}
  <link href="{{ url_for('static', filename='css/styles.min.css') }}" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
    <header class="container header">
        <div class="header__wrapper">
          {% block header %}{% endblock %}
        </div>
        {% block search %}{% endblock %}
    </header>
    <main class="container">
    <section class="items">
    {% block flash %}{% endblock %}
    {% for post in posts %}
        <div class="items__item item">
            <div class="item__top">
              <a href="{{ url_for('post_blueprint.user_posts_page', username=post.poster_name) }}" class="item__head">
                <div class="item__ava-wrap">
                  <img src="{{ post.poster_avatar }}" alt="" class="item__ava" width="47">
                </div>
                <span class="item__username">{{ post.poster_name }}</span>
              </a>
              {% block delete_bookmark scoped %}{% endblock %}
            </div>
            <a href="{{ url_for('post_blueprint.post_page', post_id=post.pk) }}" class="item__post-link">
              <img src="{{ post.pic }}" alt="" width="348" class="item__post-img">
            </a>
            {% block content scoped %}{% endblock %}
            <div class="item__post-bottom">
              <a href="{{ url_for('post_blueprint.post_page', post_id=post.pk) }}" class="item__btn-more">Подробнее</a>
              <button type="submit" class="{% if post.pk in bookmarks_list %}item__bookmark-btn:hover{% else %}item__bookmark-btn{% endif %}">
                 <img src="/img/bookmark.png" alt="{{ post.pk }}" class="item__bookmark-icon"  width="24">
              </button>
            </div>
            <div class="item__post-info">
              <div class="item__comments-counter">
                <span>
                  {% if comments.get(post.pk) == None %}
                      0 комментариев
                  {% else %}
                      {% if comments.get(post.pk)%100 > 10 and comments.get(post.pk)%100 < 15 %}
                          {{ comments.get(post.pk) }} комментариев
                      {% elif comments.get(post.pk)%10 == 1 %}
                          {{ comments.get(post.pk) }} комментарий
                      {% elif comments.get(post.pk)%10 > 1 and comments.get(post.pk)%10 < 5 %}
                          {{ comments.get(post.pk) }} комментария
                      {% else %}
                          {{ comments.get(post.pk) }} комментариев
                      {% endif %}
                  {% endif %}
                </span>
              </div>
              <div class="item__counter">
                  <img src="/img/eye.png" alt="" class="item__counter-icon" width="26">
                  <span class="item__counter-text">{{ post.views_count }}</span>
              </div>
            </div>
            <div class="item__post-bottom">
              <button type="submit" class="{% if post.pk in likes_list %} item__bookmark-btn:hover {% else %} item__bookmark-btn {% endif %}">
                <img src="/img/like.png" alt="{{ post.pk }}" class="item__bookmark-icon" width="32">
              </button>
              <span id="like{{ post.pk }}" class="item__counter-text">{{ post.likes_count }}</span>
            </div>
            {% block users_comment scoped %}{% endblock %}
        </div>
    {% endfor %}
    {% block pagination scoped %}{% endblock %}
    </section>
  </main>
  {% block svg %}{% endblock %}
  <script>
      $(document).ready(function (){   {# определяем что страница полностью загружена для выполнения скрипта #}
          $(`.item__bookmark-icon`).click(function (){    {# отслеживаем нажитие на класс .item__like-icon #}
              let image = $(this);      {# объявили переменную image и записали туда элемент на который кликнули #}
              let count_bookmark = $('.header__bookmark-counter');
              let postId = image.attr('alt');  {# получили содержимое alt от элемента на который кликнули #}
              let parent_button = image.parent('button'); {# получили у родителя элемента на который кликнули всю информацию по тегу button #}
              let image_type = image.attr('src');
              let likes_counter = document.getElementById('like'+postId);
              $.ajax({
                  type: "POST",
                  url: "{{ url_for('post_blueprint.get_like_and_bookmark') }}",
                  data: {
                      post_id: postId,
                      element: image_type
                  },
                  success: function (data) {
                      let status = data['status'];
                      let bookmark_list = data['bookmark_list'];
                      let likes_count = data['likes_count'];
                      if (status) {
                          count_bookmark.text(bookmark_list);
                          parent_button.attr('class', 'item__bookmark-btn:hover');
                          likes_counter.textContent = likes_count;
                      } else {
                          count_bookmark.text(bookmark_list);
                          parent_button.attr('class', 'item__bookmark-btn');
                          likes_counter.textContent = likes_count;
                      }
                  }
              });
          })
      });
  </script>
</body>
</html>

app/blueprints/post_blueprint/templates/post.html
{% extends "base.html" %}

{% block title %}SKYPROGRAM post{% endblock %}

{% block header %}
<a href="{{ url_for('post_blueprint.page_index') }}" class="header__btn-back">
    <svg class="header__btn-icon" width="19" height="16">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#back"></use>
    </svg>
</a>
<a href="{{ url_for('post_blueprint.page_index') }}" class="header__logo-link">
    <svg class="header__logo" width="64" height="26">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#post"></use>
    </svg>
</a>
{% endblock %}

{% block flash %}
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <ul class=flashes style="padding-left: 0;">
            {% for category, message in messages %}
                <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endwith %}
{% endblock %}

{% block content %}
    <div class="item__descr">
      <p class="item__text">
        {{ post.content|safe }}
      </p>
    </div>
{% endblock %}

{% block users_comment scoped %}
<div class="item__comments">
      {% for comment_text in comments_text %}
        <p class="item__comment">
          <b>{{ comment_text.commenter_name }}:</b> {{ comment_text.comment }}
        </p>
      {% endfor %}
</div>
<div>
  <form action="{{ url_for('post_blueprint.post_page', post_id=post.pk) }}" method="post">
     <label>
         <textarea name="name" type="text" maxlength="20" class="add_post__input" placeholder="Ваше имя" style="height: 60px"></textarea>
     </label>
     <label>
         <textarea class="add_post__input" name="comment" placeholder="Ваш комментарий" style="height: 300px"></textarea>
     </label>
     <button type="submit" style="background-color: black; color: white">Отправить</button>
  </form>
</div>
{% endblock %}

{% block svg %}
  <svg xmlns="http://www.w3.org/2000/svg" style="display:none">
    <symbol id="back" viewbox="0 0 19 16" fill="none" width="19" height="16">
      <path d="m17.34 6.19.028.006H5.074L8.94 2.322c.19-.189.293-.445.293-.714 0-.269-.104-.523-.293-.713L8.338.294A.997.997 0 0 0 7.628 0a.997.997 0 0 0-.71.293L.293 6.917A.995.995 0 0 0 0 7.63c0 .27.103.524.293.713l6.625 6.625c.189.189.441.293.71.293.269 0 .52-.104.71-.293l.601-.602a.995.995 0 0 0 .293-.71.965.965 0 0 0-.293-.696L5.031 9.064h12.322c.554 0 1.02-.477 1.02-1.03v-.851c0-.554-.48-.994-1.033-.994Z" fill="#000" />
    </symbol>
    <symbol id="post" viewbox="0 0 64 26" fill="none" width="64" height="26">
      <path d="M5.88 25v-8.48h2.208c4.416 0 7.232-2.528 7.232-7.2V8.04C15.32 3.432 12.504 1 8.088 1H.6v24h5.28ZM7.832 5.48c1.536 0 2.432.768 2.432 2.88V9c0 2.176-.896 3.04-2.432 3.04H5.88V5.48h1.952Zm17.257 20c4.864 0 7.84-2.752 7.84-8.32V8.84c0-5.568-2.976-8.32-7.84-8.32s-7.84 2.752-7.84 8.32v8.32c0 5.568 2.976 8.32 7.84 8.32Zm0-4.64c-1.504 0-2.4-.864-2.4-3.52V8.68c0-2.656.928-3.52 2.4-3.52 1.504 0 2.4.864 2.4 3.52v8.64c0 2.656-.896 3.52-2.4 3.52ZM35.243 6.952c0 3.264 1.44 5.184 3.52 6.752l2.56 1.952c1.664 1.28 2.624 2.016 2.624 3.648 0 1.152-.704 1.856-1.888 1.856-1.152 0-1.92-.896-1.92-2.304V17h-5.12v2.08c0 4.128 3.168 6.4 7.04 6.4s7.04-2.24 7.04-6.816c0-3.104-1.536-5.056-3.584-6.592l-2.656-2.048c-1.568-1.184-2.496-1.888-2.496-3.456 0-1.12.704-1.728 1.664-1.728 1.056 0 1.728.704 1.728 2.176V8.68h5.024V6.92c0-4.32-2.976-6.4-6.752-6.4-3.712 0-6.784 1.824-6.784 6.432ZM59.414 25V5.64h3.904V1H50.07v4.64h3.904V25h5.44Z" fill="#000" fill-opacity=".8" />
    </symbol>
  </svg>
{% endblock %}

app/blueprints/post_blueprint/templates/search.html
{% extends "base.html" %}

{% block title %}SKYPROGRAM search{% endblock %}

{% block user_style %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
{% endblock %}

{% block header %}
  <a href="{{ url_for('post_blueprint.page_index') }}" class="header__btn-back">
    <svg class="header__btn-icon" width="19" height="16">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#back"></use>
    </svg>
  </a>
  <a href="{{ url_for('post_blueprint.page_index') }}" class="header__logo-link">
    <svg class="header__logo" width="100" height="26">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#search"></use>
    </svg>
  </a>
{% endblock %}

{% block content %}
<p class="item__descr">{{ post.content[:50] }}...</p>
{% endblock %}

{% block pagination scoped %}
    {{ pagination.links }}
{% endblock %}

{% block svg %}
  <svg xmlns="http://www.w3.org/2000/svg" style="display:none">
    <symbol id="back" viewbox="0 0 19 16" fill="none" width="19" height="16">
      <path d="m17.34 6.19.028.006H5.074L8.94 2.322c.19-.189.293-.445.293-.714 0-.269-.104-.523-.293-.713L8.338.294A.997.997 0 0 0 7.628 0a.997.997 0 0 0-.71.293L.293 6.917A.995.995 0 0 0 0 7.63c0 .27.103.524.293.713l6.625 6.625c.189.189.441.293.71.293.269 0 .52-.104.71-.293l.601-.602a.995.995 0 0 0 .293-.71.965.965 0 0 0-.293-.696L5.031 9.064h12.322c.554 0 1.02-.477 1.02-1.03v-.851c0-.554-.48-.994-1.033-.994Z" fill="#000" />
    </symbol>
    <symbol id="search" viewbox="0 0 100 26" fill="none" width="100" height="26">
      <path d="M1.024 6.952c0 3.264 1.44 5.184 3.52 6.752l2.56 1.952c1.664 1.28 2.624 2.016 2.624 3.648 0 1.152-.704 1.856-1.888 1.856-1.152 0-1.92-.896-1.92-2.304V17H.8v2.08c0 4.128 3.168 6.4 7.04 6.4s7.04-2.24 7.04-6.816c0-3.104-1.536-5.056-3.584-6.592L8.64 10.024C7.072 8.84 6.144 8.136 6.144 6.568c0-1.12.704-1.728 1.664-1.728 1.056 0 1.728.704 1.728 2.176V8.68h5.024V6.92c0-4.32-2.976-6.4-6.752-6.4-3.712 0-6.784 1.824-6.784 6.432ZM29.099 20.36h-6.592v-5.28h5.952v-4.64h-5.952v-4.8H29.1V1H17.131v24H29.1v-4.64ZM34 1l-3.777 24h5.216l.576-4.32h4.416l.577 4.32h5.215L42.447 1H34Zm2.623 15.2 1.6-11.68 1.6 11.68h-3.2ZM53.352 25V13.192L57.671 25h5.984l-4.64-11.104c2.432-.832 4.032-2.752 4.032-5.728V7.24c0-4.064-2.976-6.24-7.072-6.24h-8v24h5.376Zm1.888-19.52c1.504 0 2.432.704 2.432 2.688v.448c0 2.144-.928 3.008-2.432 3.008h-1.888V5.48h1.888Zm20.25 9.28v2.56c0 2.624-.896 3.52-2.4 3.52s-2.4-.896-2.4-3.52V8.68c0-2.656.928-3.52 2.4-3.52 1.504 0 2.4.864 2.4 3.52v2.24h5.44V8.84c0-5.568-2.976-8.32-7.84-8.32s-7.84 2.752-7.84 8.32v8.32c0 5.568 2.976 8.32 7.84 8.32s7.84-2.752 7.84-8.32v-2.4h-5.44ZM89.259 25v-9.984h4.8V25h5.44V1h-5.44v9.344h-4.8V1h-5.44v24h5.44Z" fill="#000" fill-opacity=".8" />
    </symbol>
  </svg>
{% endblock %}

app/blueprints/post_blueprint/templates/tag.html
{% extends "base.html" %}

{% block title %}SKYPROGRAM tag{% endblock %}

{% block user_style %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
{% endblock %}

{% block header %}
  <a href="{{ url_for('post_blueprint.page_index') }}" class="header__btn-back">
    <svg class="header__btn-icon" width="19" height="16">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#back"></use>
    </svg>
  </a>
  <a href="{{ url_for('post_blueprint.search_hashtag', tag_name=tag_name) }}" class="header__nosvg">
    ТЭГ / {{ tag_name }}
  </a>
{% endblock %}

{% block content %}
<p class="item__descr">
    <a href="{{ url_for('post_blueprint.search_hashtag', tag_name=tag_name) }}" class="item__tag">#{{ tag_name }}</a>
    {{ post.content[:50] }}...
</p>
{% endblock %}

{% block pagination scoped %}
{{ pagination.links }}
{% endblock %}

{% block svg %}
  <svg xmlns="http://www.w3.org/2000/svg" style="display:none">
    <symbol id="back" viewbox="0 0 19 16" fill="none" width="19" height="16">
      <path d="m17.34 6.19.028.006H5.074L8.94 2.322c.19-.189.293-.445.293-.714 0-.269-.104-.523-.293-.713L8.338.294A.997.997 0 0 0 7.628 0a.997.997 0 0 0-.71.293L.293 6.917A.995.995 0 0 0 0 7.63c0 .27.103.524.293.713l6.625 6.625c.189.189.441.293.71.293.269 0 .52-.104.71-.293l.601-.602a.995.995 0 0 0 .293-.71.965.965 0 0 0-.293-.696L5.031 9.064h12.322c.554 0 1.02-.477 1.02-1.03v-.851c0-.554-.48-.994-1.033-.994Z" fill="#000" />
    </symbol>
    <symbol id="tag" viewbox="0 0 144 26" fill="none" width="144" height="26">
      <path d="M9.664 25V5.64h3.904V1H.32v4.64h3.904V25h5.44Zm7.178-24-3.776 24h5.216l.576-4.32h4.416L23.85 25h5.216L25.29 1h-8.448Zm2.624 15.2 1.6-11.68 1.6 11.68h-3.2Zm17.532 9.28c2.273 0 4.033-.928 5.056-2.848V25h3.968V12.04h-8.16v4.32h2.72v1.12c0 2.464-.928 3.36-2.4 3.36-1.504 0-2.4-.896-2.4-3.52V8.68c0-2.656.929-3.52 2.4-3.52 1.505 0 2.4.864 2.4 3.52v1.344h5.44V8.84c0-5.568-2.975-8.32-7.84-8.32-4.864 0-7.84 2.752-7.84 8.32v8.32c0 5.568 2.56 8.32 6.657 8.32ZM59.58 25l8-24h-3.84l-8 24h3.84Zm23.24 0v-9.28h5.472v-4.64H82.82V5.64h6.272V1H77.444v24h5.376Zm16.019.48c4.864 0 7.84-2.752 7.84-8.32V8.84c0-5.568-2.976-8.32-7.84-8.32s-7.84 2.752-7.84 8.32v8.32c0 5.568 2.976 8.32 7.84 8.32Zm0-4.64c-1.504 0-2.4-.864-2.4-3.52V8.68c0-2.656.928-3.52 2.4-3.52 1.504 0 2.4.864 2.4 3.52v8.64c0 2.656-.896 3.52-2.4 3.52Zm18.25 4.64c4.864 0 7.84-2.752 7.84-8.32V8.84c0-5.568-2.976-8.32-7.84-8.32s-7.84 2.752-7.84 8.32v8.32c0 5.568 2.976 8.32 7.84 8.32Zm0-4.64c-1.504 0-2.4-.864-2.4-3.52V8.68c0-2.656.928-3.52 2.4-3.52 1.504 0 2.4.864 2.4 3.52v8.64c0 2.656-.896 3.52-2.4 3.52ZM135.339 1h-7.52v24h7.52c4.864 0 7.84-2.688 7.84-8.16V9.16c0-5.472-2.976-8.16-7.84-8.16Zm0 19.36h-2.08V5.64h2.08c1.504 0 2.4.832 2.4 3.36v8c0 2.528-.896 3.36-2.4 3.36Z" fill="#000" fill-opacity=".8" />
    </symbol>
  </svg>
{% endblock %}